main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('courses/by_subject/<int:subject_id>/', views.CoursesBySubject.as_view(), name='by-subject'),
    path('courses/by_subcategory/<int:subcategory_id>/', views.CoursesBySubcategory.as_view(), name='by-subcategory'),
    path('courses/by_category/<int:category_id>/', views.CoursesByCategory.as_view(), name='by-category'),
    path('mycourses/create/', views.CourseCreateView.as_view(), name='add'),
    path('mycourses/<int:id>/preview/', views.CoursePreviewView.as_view(), name='preview'),
    path('mycourses/<slug:slug>/', views.CourseContentView.as_view(), name='content'),
    path('mycourses/<slug:slug>/edit/', views.CourseEditView.as_view(), name='edit'),
    path('course/<slug:slug>/', views.CourseDetailView.as_view(), name='single'),
    path('search', views.CourseSearchView.as_view(), name='search'),
    path('webhook/', views.my_webhook_view),
]

project_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='course')),
    path('', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('auth/', include(('users.urls', 'users'), namespace='users')),
    path('api/', include(('core.api_urls', 'core'), namespace='api')),
    path('statistic/', include(('statistic.urls', 'statistic'), namespace='statistics')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

statistic/urls.py
from django.urls import path
from statistic.views import CategoryStatisticsView, CourseBySubjectStatisticsView, SubCategoryStatisticsView, SubjectStatisticsView


urlpatterns = [
    path('main/', CategoryStatisticsView.as_view(), name='main'),
    path('subcategories/by_category/<int:id>/', SubCategoryStatisticsView.as_view(), name='subcategories'),
    path('subjects/by_subcategory/<int:id>/', SubjectStatisticsView.as_view(), name='subjects'),
    path('courses/by_subject/<int:id>/', CourseBySubjectStatisticsView.as_view(), name='courses'),
]

statistic/api/views.py
from rest_framework import generics
from categories.models import Category, SubCategory, Subject
from courses.models import Course
from .serializers import CategoryStatisticsSerializer, CourseStatisticsSerializer, SubCategoryStatisticsSerializer, SubjectStatisticsSerializer


class CategoryStatisticsView(generics.ListAPIView):
    queryset = Category.statistics.all()
    serializer_class = CategoryStatisticsSerializer


class SubCategoryStatisticsView(generics.ListAPIView):
    serializer_class = SubCategoryStatisticsSerializer

    def get_queryset(self):
        category_id = self.kwargs.get('id')
        return SubCategory.statistics.by_category(category_id=category_id)
    

class SubjectStatisticsView(generics.ListAPIView):
    serializer_class = SubjectStatisticsSerializer

    def get_queryset(self):
        subcategory_id = self.kwargs.get('id')
        return Subject.statistics.by_subcategory(subcategory_id=subcategory_id)


class CourseStatisticsView(generics.ListAPIView):
    serializer_class = CourseStatisticsSerializer

    def get_queryset(self):
        subject_id = self.kwargs.get('id')
        return Course.statistics.by_subject(subject_id=subject_id)

statistic/views.py
from django.views.generic import TemplateView


class CategoryStatisticsView(TemplateView):
    template_name = 'statistic-main.html'


class SubCategoryStatisticsView(TemplateView):
    template_name = 'statistic-subcategories.html'


class SubjectStatisticsView(TemplateView):
    template_name = 'statistic-subjects.html'


class CourseBySubjectStatisticsView(TemplateView):
    template_name = 'statistic-courses.html'

statistic/templates/statistic-courses.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти на сайт{% endblock title %}
{% block imports %}
<link href="{% static 'statistic-main.css' %}" rel="stylesheet">
<script src="{% static 'statistic-courses.js' %}" defer></script>
{% endblock imports %}  
{% block content %}
<div class="invisible">
    <p id="subject-id">{{ id }}</p>
</div>
<div class="main-body">
    <p>Statistic</p>
    <a href="{% url 'statistic:subjects' id %}">Вернуться в подкатегорию</a>
    <template id="template-stats">
        <div class="stats-row">
            <span class="course-id"></span>
            <a class="course-name"></a>
            <span class="course-reviews"></span>
            <span class="course-rating"></span>
            <span class="course-students"></span>
            <span class="course-payments"></span>
            <span class="course-month-payments"></span>
        </div>
    </template>
    <div id="stats">
        <div class="stats-header">
            <span class="course-id">id</span>
            <span class="course-name">name</span>
            <span class="course-reviews">reviews</span>
            <span class="course-rating">rating</span>
            <span class="course-students">students</span>
            <span class="course-payments">payments</span>
            <span class="course-month-payments">last month payments</span>
        </div>
    </div>
</div>
{% endblock content %} 

statistic/templates/statistic-main.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти на сайт{% endblock title %}
{% block imports %}
<link href="{% static 'statistic-main.css' %}" rel="stylesheet">
<script src="{% static 'statistic-main.js' %}" defer></script>
{% endblock imports %}  
{% block content %}
<div class="main-body">
    <p>Statistic</p>
    <template id="template-stats">
        <div class="stats-row">
            <span class="cat-id"></span>
            <a class="cat-name"></a>
            <span class="cat-authors"></span>
            <span class="cat-courses"></span>
            <span class="cat-students"></span>
            <span class="cat-payments"></span>
            <span class="cat-month-payments"></span>
        </div>
    </template>
    <div id="stats">
        <div class="stats-header">
            <span class="cat-id">id</span>
            <span class="cat-name">name</span>
            <span class="cat-authors">authors</span>
            <span class="cat-courses">courses</span>
            <span class="cat-students">students</span>
            <span class="cat-payments">payments</span>
            <span class="cat-payments">last month payments</span>
        </div>
    </div>
</div>
{% endblock content %} 

statistic/templates/statistic-subcategories.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти на сайт{% endblock title %}
{% block imports %}
<link href="{% static 'statistic-main.css' %}" rel="stylesheet">
<script src="{% static 'statistic-subcategories.js' %}" defer></script>
{% endblock imports %}  
{% block content %}
<div class="invisible">
    <p id="cat-id">{{ id }}</p>
</div>
<div class="main-body">
    <p>Statistic</p>
    <a href="{% url 'statistic:main' %}">Вернуться в категории</a>
    <template id="template-stats">
        <div class="stats-row">
            <span class="subcat-id"></span>
            <a class="subcat-name"></a>
            <span class="subcat-authors"></span>
            <span class="subcat-courses"></span>
            <span class="subcat-students"></span>
            <span class="subcat-payments"></span>
            <span class="subcat-month-payments"></span>
        </div>
    </template>
    <div id="stats">
        <div class="stats-header">
            <span class="subcat-id">id</span>
            <span class="subcat-name">name</span>
            <span class="subcat-authors">authors</span>
            <span class="subcat-courses">courses</span>
            <span class="subcat-students">students</span>
            <span class="subcat-payments">payments</span>
            <span class="subcat-payments">last month payments</span>
        </div>
    </div>
</div>
{% endblock content %} 

statistic/templates/statistic-subjects.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти на сайт{% endblock title %}
{% block imports %}
<link href="{% static 'statistic-main.css' %}" rel="stylesheet">
<script src="{% static 'statistic-subjects.js' %}" defer></script>
{% endblock imports %}  
{% block content %}
<div class="invisible">
    <p id="subcat-id">{{ id }}</p>
</div>
<div class="main-body">
    <p>Statistic</p>
    <a href="{% url 'statistic:subcategories' id %}">Вернуться в подкатегорию</a>
    <template id="template-stats">
        <div class="stats-row">
            <span class="subject-id"></span>
            <a class="subject-name"></a>
            <span class="subject-authors"></span>
            <span class="subject-courses"></span>
            <span class="subject-students"></span>
            <span class="subject-payments"></span>
            <span class="subject-month-payments"></span>
        </div>
    </template>
    <div id="stats">
        <div class="stats-header">
            <span class="subject-id">id</span>
            <span class="subject-name">name</span>
            <span class="subject-authors">authors</span>
            <span class="subject-courses">courses</span>
            <span class="subject-students">students</span>
            <span class="subject-payments">payments</span>
            <span class="subject-payments">last month payments</span>
        </div>
    </div>
</div>
{% endblock content %} 