main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('courses/by_subject/<int:subject_id>/', views.CoursesBySubject.as_view(), name='by-subject'),
    path('courses/by_subcategory/<int:subcategory_id>/', views.CoursesBySubcategory.as_view(), name='by-subcategory'),
    path('courses/by_category/<int:category_id>/', views.CoursesByCategory.as_view(), name='by-category'),
    path('mycourses/create/', views.CourseCreateView.as_view(), name='add'),
    path('mycourses/<int:id>/preview/', views.CoursePreviewView.as_view(), name='preview'),
    path('mycourses/<slug:slug>/', views.CourseContentView.as_view(), name='content'),
    path('mycourses/<slug:slug>/edit/', views.CourseEditView.as_view(), name='edit'),
    path('course/<slug:slug>/', views.CourseDetailView.as_view(), name='single'),
    path('search', views.CourseSearchView.as_view(), name='search'),
    path('webhook/', views.my_webhook_view),
]

profiles/urls.py
from django.urls import path

from profiles.views import MyCoursesView, MyProfileView, TeacherProfileView


urlpatterns = [path('myprofile/', MyProfileView.as_view(), name='my'),
               path('teacher/<int:id>/', TeacherProfileView.as_view(), name='teacher'),
               path('mycourses/', MyCoursesView.as_view(), name='my-courses')
            ]

project_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='course')),
    path('', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('auth/', include(('users.urls', 'users'), namespace='users')),
    path('api/', include(('core.api_urls', 'core'), namespace='api')),
    path('statistic/', include(('statistic.urls', 'statistic'), namespace='statistics')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class TeacherProfile(models.Model):
    avatar = models.ImageField(upload_to='media/profiles/avatars/')
    bio = models.CharField(max_length=2000)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    balance = models.PositiveIntegerField(default=0)

    def __str__(self) -> str:
        return f'Profile for user id={self.user.id}'

profiles/api/views.py
from rest_framework.response import Response
from rest_framework.views import APIView
from ..models import TeacherProfile
from .serializers import TeacherProfileSerializer
from courses.models import Course
from courses.api.serializers import CourseSearchSerializer


class HasTeacherProfile(APIView):
    def get(self, request):
        teacher_profile = TeacherProfile.objects.filter(user=request.user)
        if teacher_profile.exists():
            serializer = TeacherProfileSerializer(teacher_profile[0])
            courses = Course.custom_objects.by_author(author=request.user)
            courses_data = CourseSearchSerializer(courses, many=True).data
            return Response({'profile': True, 'content': serializer.data, 'courses': courses_data})
        else:
            return Response({'profile': False})

profiles/views.py
from django.views.generic import TemplateView


class MyProfileView(TemplateView):
    template_name = 'my-profile.html'


class TeacherProfileView(TemplateView):
    template_name = 'teacher-page.html'


class MyCoursesView(TemplateView):
    template_name = 'my-courses.html'

profiles/templates/my-courses.html
{% extends "base.html" %}
{% load static %}
{% block imports %}
<link href="{% static 'my-profile.css' %}" rel="stylesheet">
<script src="{% static 'my-courses.js' %}" defer></script>
{% endblock imports %}
{% block title %}My profile{% endblock title %}
{% block content %}
<div class="main-body">
    <template id="template-course">
        <div class="course-wrapper">
            <img class="course-cover">
            <div class="course-info">
                <a class="course-link"><h3 class="course-title"></h3><a>
                <p class="course-description"></p>
                <p>Рейтинг: <span class="course-rating"></span></p>
                <p>Студентов: <span class="course-students"></span></p>
            </div>
            <div class="course-buttons">
            </div>
        </div>
    </template>
    <div id="my-courses"></div>
</div>
{% endblock content %}

profiles/templates/my-profile.html
{% extends "base.html" %}
{% load static %}
{% block imports %}
<link href="{% static 'my-profile.css' %}" rel="stylesheet">
<script src="{% static 'my-profile.js' %}" defer></script>
{% endblock imports %}
{% block title %}My profile{% endblock title %}
{% block content %}
<div class="invisible">
    <p id="csrf-token">{% csrf_token %}</p>
</div>
<div class="main-body">
    <div id="profile-create" class="invisible">
        <form name="profile-form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-wrapper">
                <div class="form-field">
                    <label for="cover">Аватарка</label>
                    <input type="file" name="avatar">
                </div>
                <div class="form-field">
                    <label for="bio">Подробное био</label>
                    <textarea name="bio" cols="50" rows="8"></textarea>
                </div>  
            </div>
            <button class="form-button" type="submit">Создать профиль</button>
        </form>
    </div>
    <div id="profile">
        <img id="profile-avatar">
        <div>
            <h3 id="author-name"></h3>
            <p id="profile-bio">Изменить био</p>
            <p>Общий рейтинг всех курсов: <span id="courses-rating"></span></p>
            <p>Общее количество студентов: <span id="courses-students"></span></p>
        </div>
        <div>
            <p>Баланс: <span id="balance"></span></p>
        </div>
        
    </div>
    <a class="form-button" href="{% url 'course:add' %}">Добавить курс</a>
    <template id="template-course">
        <div class="course-wrapper">
            <img class="course-cover">
            <div class="course-info">
                <h3 class="course-title"></h3>
                <p class="course-description"></p>
                <p>Количество студентов: <span class="course-students"></span></p>
                <p>Рейтинг: <span class="course-rating"></span></p>
            </div>
            <div class="course-buttons">
                <button class="form-button btn-unpublish invisible">Снять с публикации</button>
                <button class="form-button btn-publish invisible">Опубликовать</button>
                <button class="form-button btn-content">Изменить контент</button>
                <button class="form-button btn-edit">Изменить информацию</button>
            </div>
        </div>
    </template>
    <div id="my-courses"></div>
</div>
{% endblock content %}

profiles/templates/teacher-page.html
{% extends "base.html" %}
{% load static %}
{% block imports %}
<link href="{% static 'teacher-page.css' %}" rel="stylesheet">
<script src="{% static 'teacher-page.js' %}" defer></script>
{% endblock imports %}
{% block title %}My profile{% endblock title %}
{% block content %}
<div class="main-body">
    <div class="invisible">
        <p id="author-id">{{ id }}</p>
        <svg id="icon-star" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
    </div>
    <div id="teacher-block">
        <img id="teacher-avatar">
        <div id="techaer-block-right">
            <h3 id="teacher-name"></h3>
            <div id="teacher-rating-block">
                <span>Рейтинг: </span>
                <div class="teacher-rating">
                    <svg class="review-star-small">
                        <use href="#icon-star"></use>
                    </svg>
                    <svg class="review-star-small">
                        <use href="#icon-star"></use>
                    </svg>
                    <svg class="review-star-small">
                        <use href="#icon-star"></use>
                    </svg>
                    <svg class="review-star-small">
                        <use href="#icon-star"></use>
                    </svg>
                    <svg class="review-star-small">
                        <use href="#icon-star"></use>
                    </svg>
                    <span class="course-rating-number"></span>
                </div>
                <span id="teacher-rating"></span>
            </div>
            <div>
                <span>Студентов: </span>
                <span id="teacher-students"></span>
            </div>
            <span>Био:</span>
            <p id="teacher-bio"></p>
        </div>
    </div>
    <div id="courses-block">
        <h3>Курсы преподавателя:</h3>
        <template id="template-course">
            <div class="course-wrapper">
                <div class="course-cover">
                    <img>
                </div>
                <div class="course-body">
                    <a><h3 class="course-name"></h3></a>
                    <p class="course-description"></p>
                    <span>Студентов: <span class="course-student-count"></span></span>
                    <div class="course-rating">
                        <svg class="review-star-small">
                            <use href="#icon-star"></use>
                        </svg>
                        <svg class="review-star-small">
                            <use href="#icon-star"></use>
                        </svg>
                        <svg class="review-star-small">
                            <use href="#icon-star"></use>
                        </svg>
                        <svg class="review-star-small">
                            <use href="#icon-star"></use>
                        </svg>
                        <svg class="review-star-small">
                            <use href="#icon-star"></use>
                        </svg>
                        <span class="course-rating-number"></span>
                    </div>
                    <div class="course-subject">
                        <span></span>
                    </div>
                </div>
                <div class="course-price">
                    <span></span>
                </div>
            </div>
        </template>
        <div id="courses">
            
        </div>
    </div>
</div>
{% endblock content %}