main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('courses/by_subject/<int:subject_id>/', views.CoursesBySubject.as_view(), name='by-subject'),
    path('courses/by_subcategory/<int:subcategory_id>/', views.CoursesBySubcategory.as_view(), name='by-subcategory'),
    path('courses/by_category/<int:category_id>/', views.CoursesByCategory.as_view(), name='by-category'),
    path('mycourses/create/', views.CourseCreateView.as_view(), name='add'),
    path('mycourses/<int:id>/preview/', views.CoursePreviewView.as_view(), name='preview'),
    path('mycourses/<slug:slug>/', views.CourseContentView.as_view(), name='content'),
    path('mycourses/<slug:slug>/edit/', views.CourseEditView.as_view(), name='edit'),
    path('course/<slug:slug>/', views.CourseDetailView.as_view(), name='single'),
    path('search', views.CourseSearchView.as_view(), name='search'),
    path('webhook/', views.my_webhook_view),
]

project_courses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='course')),
    path('', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('auth/', include(('users.urls', 'users'), namespace='users')),
    path('api/', include(('core.api_urls', 'core'), namespace='api')),
    path('statistic/', include(('statistic.urls', 'statistic'), namespace='statistics')),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, LoginView
from .forms import UserLoginForm


urlpatterns = [
    path('register/', views.registration, name='registration'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(template_name='login.html', authentication_form=UserLoginForm), name='login')
]

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
import stripe
from decouple import config
from .payment import fullfill_order

stripe.api_key = config('STRIPE_KEY')

endpoint_secret = config('STRIPE_WEBHOOK_SECRET')


class IndexView(TemplateView):
  template_name = 'index.html'


class CourseCreateView(TemplateView):
  template_name = 'course-add.html'


class CoursePreviewView(TemplateView):
  template_name = 'course-preview.html'


class CourseContentView(TemplateView):
  template_name = 'course-content.html'


class CourseDetailView(TemplateView):
  template_name = 'course-single.html'


class CourseSearchView(TemplateView):
  template_name = 'search.html'


class CoursesBySubject(TemplateView):
  template_name = 'by_subject.html'


class CoursesBySubcategory(TemplateView):
  template_name = 'by_subcategory.html'

class CoursesByCategory(TemplateView):
  template_name = 'by_category.html'

class CourseEditView(TemplateView):
  template_name = 'course-edit.html'


@csrf_exempt
def my_webhook_view(request):
  payload = request.body
  sig_header = request.META['HTTP_STRIPE_SIGNATURE']
  event = None

  try:
    event = stripe.Webhook.construct_event(
      payload, sig_header, endpoint_secret
    )
  except ValueError as e:
    # Invalid payload
    return HttpResponse(status=400)
  except stripe.error.SignatureVerificationError as e:
    # Invalid signature
    return HttpResponse(status=400)
  
  if event['type'] == 'checkout.session.completed':
    # Retrieve the session. If you require line items in the response, you may include them by expanding line_items.
    session = stripe.checkout.Session.retrieve(
      event['data']['object']['id'],
      expand=['line_items'],
    )
    line_items = session.line_items
    # Fulfill the purchase...
    fullfill_order(product_data=line_items['data'][0], client_id=session['client_reference_id'], metadata=session['metadata'])

  # Passed signature verification
  return HttpResponse(status=200)

main/templates/base.html
{% load static %}
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="{% static 'shared.css' %}" rel="stylesheet">
    <link href="{% static 'forms.css' %}" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Geologica&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Geologica:wght@100&display=swap" rel="stylesheet">
    <script src="{% static 'script.js' %}" defer></script>
    {% block imports %}{% endblock imports %}
</head>
<div id="backdrop" class="invisible"></div>
<template id="header-search-template">
    <li class="header-search-element">
        <img class="search-element-cover" alt="">
        <a class="search-element-name"></a>
        <span class="search-element-price"></span>
    </li>
</template>
<nav>
    <div class="header">
        <ul class="header-items">
            <li class="header-item" id="header-logo">
                <span>courses!</span>
            </li>
            <li class="header-item" id="header-categories">
                <span id="header-categories-link">Категории</span>
                <template id="header-popover-template">
                    <div class="header-popover-element">
                        <a class="header-popover-link"></a>
                    </div>
                </template>
                <div id="header-popover-categories" class="invisible"></div>
                <div id="header-popover-subcategories" class="invisible"></div>
                <div id="header-popover-subjects" class="invisible"></div>
            </li>
            <li class="header-item" id="header-search">
                <div class="header-search-field">
                    <form action="/search">
                        <input type="text" name="query" id="header-search-input">
                    </form>
                    <div id="header-search-body" class="invisible">
                        <ul class="search-elements">

                        </ul>
                    </div>
                </div>
            </li>
            <li class="header-item">
                <span>Стать преподавателем</span>
            </li>
            {% if request.user|has_group:"teachers" %} 
            <li class="header-item">
                <a href="/myprofile/">Мой профиль</a>
            </li>
            {% elif user.is_authenticated %}
            <li class="header-item">
                <a href="/mycourses/">Мои курсы</a>
            </li>
            {% endif %}
            <li class="header-item">
                {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                <a href="{% url 'users:login' %}">Войти</a>
                {% endif %}
            </li>
            <li class="header-item">
                <a href="{% url 'users:registration' %}">Регистрация</a>
            </li>
        </ul>
    </div>
</nav>

<body>
{% block content %}{% endblock content %}
</body>
</html>

main/templates/by_category.html
{% extends "base.html" %}
{% load static %}
{% block imports %}
<link href="{% static 'search.css' %}" rel="stylesheet">
<link href="{% static 'courses.css' %}" rel="stylesheet">
<script src="{% static 'by-category.js' %}" type="module" defer></script>
{% endblock imports %}
{% block title %}By category{% endblock title %}
{% block content %}
<div class="invisible">
    <p id="category-id">{{ category_id }}</p>
</div>
<template id="template-course">
    <div class="course-wrapper">
        <div class="course-cover">
            <img>
        </div>
        <div class="course-body">
            <a><h3 class="course-name"></h3></a>
            <p class="course-description"></p>
            <span class="course-author"></span>
            <span>Студентов: <span class="course-student-count"></span></span>
            <div class="course-rating">
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <span class="course-rating-number"></span>
            </div>
        </div>
        <div class="course-price">
            <span></span>
        </div>
    </div>
</template>
<div class="invisible">
    <svg id="icon-star" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
</div>
<div class="main-body-block">
    <p>Курсы по подкатегории <span id="subcategory-name"></span></p>  
    <div id="test-wrapper">
        <div id="courses"></div>
    </div>
    <div id="paging">
    </div>
</div>
{% endblock content %}

main/templates/by_subcategory.html
{% extends "base.html" %}
{% load static %}
{% block imports %}
<link href="{% static 'search.css' %}" rel="stylesheet">
<link href="{% static 'courses.css' %}" rel="stylesheet">
<script src="{% static 'by-subcategory.js' %}" type="module" defer></script>
{% endblock imports %}
{% block title %}By subcategory{% endblock title %}
{% block content %}
<div class="invisible">
    <p id="subcategory-id">{{ subcategory_id }}</p>
</div>
<template id="template-course">
    <div class="course-wrapper">
        <div class="course-cover">
            <img>
        </div>
        <div class="course-body">
            <a><h3 class="course-name"></h3></a>
            <p class="course-description"></p>
            <span class="course-author"></span>
            <span>Студентов: <span class="course-student-count"></span></span>
            <div class="course-rating">
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <span class="course-rating-number"></span>
            </div>
        </div>
        <div class="course-price">
            <span></span>
        </div>
    </div>
</template>
<div class="invisible">
    <svg id="icon-star" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
</div>
<div class="main-body-block">
    <p>Курсы по подкатегории <span id="subcategory-name"></span></p>  
    <div id="test-wrapper">
        <div id="courses"></div>
    </div>
    <div id="paging">
    </div>
</div>
{% endblock content %}

main/templates/by_subject.html
{% extends "base.html" %}
{% load static %}
{% block imports %}
<link href="{% static 'search.css' %}" rel="stylesheet">
<link href="{% static 'courses.css' %}" rel="stylesheet">
<script src="{% static 'by-subject.js' %}" type="module" defer></script>
{% endblock imports %}
{% block title %}By subject{% endblock title %}
{% block content %}
<div class="invisible">
    <p id="subject-id">{{ subject_id }}</p>
</div>
<template id="template-course">
    <div class="course-wrapper">
        <div class="course-cover">
            <img>
        </div>
        <div class="course-body">
            <a><h3 class="course-name"></h3></a>
            <p class="course-description"></p>
            <span class="course-author"></span>
            <span>Студентов: <span class="course-student-count"></span></span>
            <div class="course-rating">
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <svg class="review-star-small">
                    <use href="#icon-star"></use>
                </svg>
                <span class="course-rating-number"></span>
            </div>
        </div>
        <div class="course-price">
            <span></span>
        </div>
    </div>
</template>
<div class="invisible">
    <svg id="icon-star" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
</div>
<div class="main-body-block">
    <p>Курсы по предмету <span id="subject-name"></span></p>  
    <div id="test-wrapper">
        <div id="courses"></div>
    </div>
    <div id="paging">
    </div>
</div>
{% endblock content %}

main/templates/course-add.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти на сайт{% endblock title %}
{% block imports %}
<link href="{% static 'course-add.css' %}" rel="stylesheet">
<script src="{% static 'course-add.js' %}" defer></script>
{% endblock imports %}  
{% block content %}
<div class="main-body">
    <div class="invisible"><p id="csrf-token">{% csrf_token %}</p></div>
    <div class="main-content">
        <h1>Создание нового курса</h1>
        
        <div id="course-add-first-step">
            <p>Для создания нового курса заполните все необходимые поля формы, а затем перейдите к следующему этапу, на котором будет 
                необходимо ввести оставшиеся данные. 
            </p>
            <form name="course-add" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-wrapper">
                    <div class="form-field">
                        <label for="cover">Обложка курса</label>
                        <input type="file" name="cover">
                    </div>
                    <div class="form-field">
                        <label for="name">Название курса</label>
                        <input type="text" name="name" placeholder="Введите название...">
                    </div>
                    <div class="form-field">
                        <label for="short_description">Короткое описание</label>
                        <input type="text" name="short_description" placeholder="Введите краткое описание курса...">
                    </div>
                    <div class="form-field">
                        <label for="full_description">Подробное описание</label>
                        <!-- <input type="text" id="form-full-description" name="full_description" placeholder="Введите подробное описание курса..."> -->
                        <textarea name="full_description" cols="50" rows="8"></textarea>
                    </div>  
                    <div class="form-field-half">
                        <label for="price">Стоимость</label>
                        <label for="language">Язык</label>
                    </div>
                    <div class="form-field-half">
                        <input type="number" name="price" placeholder="Стоимость курса в рублях...">
                        <!-- <input type="text" name="language" placeholder="Введите язык курса..."> -->
                        <select name="language" id="select-language">
                            
                        </select>
                    </div>
                    <div class="form-field">
                        <label for="is_free">Сделать курс бесплатным</label>
                        <input type="checkbox" name="is_free"  id="is_free-checkbox">
                    </div>  
                </div>
                <button class="form-button" type="submit">Следующий шаг</button>
            </form>
        </div>
        <div id="course-add-second-step" class="invisible">
            <p>Добавьте пункты, чему обучатся студенты в процессе и начальные навыки, необходимые для начала обучения</p>
            <div id="what-will-learn">
                <div id="div-btn-what-will-learn">
                    <div class="tooltip">Нажмите для добавления нового пункта и введите значение,при необходимости повторите.</div>
                    <button class="form-button" id="btn-what-will-learn">Добавить what will learn</button>
                </div>
                    <template id="template-what-will-learn">
                        <div class="form-wrapper form-field-half">
                            <input type="text" class="what-will-learn-option">
                        </div>
                    </template>
            </div>
            <div id="requirements">
                <div id="div-btn-requirements">
                    <div class="tooltip">Нажмите для добавления нового пункта и введите значение,при необходимости повторите.</div>
                    <button class="form-button" id="btn-requirements">Добавить requirements</button>
                </div>
                    <template id="template-requirements">
                        <div class="form-wrapper form-field-half">
                            <input type="text" class="requirements-option">
                        </div>
                    </template>
            </div>
            <button class="form-button" id="course-backwards-btn">Назад</button>
            <button class="form-button" id="course-third-step-btn">Следующий шаг</button>
        </div>
        <div id="course-add-third-step" class="invisible">
            <p>Выберите уровень сложности вашего курса, а также укажите опции, которые будут доступны для студентов</p>
            <div class="form-wrapper">
                <div id="div-category" class="form-field">
                    <label for="category">Категория</label>
                    <select name="category" id="select-category">
                        <option disabled selected value>-- Выберите категорию --</option>
                    </select>
                </div>
                <div id="div-subcategory" class="form-field invisible">
                    <label for="subcategory">Подкатегория</label>
                    <select name="subcategory" id="select-subcategory">
                        <option disabled selected value>-- Выберите подкатегорию --</option>
                    </select>
                </div>
                <div id="div-subject" class="form-field invisible">
                    <label for="subject">Тема</label>
                    <select name="subject" id="select-subject">
                        <option disabled selected value>-- Выберите тему --</option>
                    </select>
                </div>
                <div class="form-field">
                    <label for="level">Уровень</label>
                    <select name="level" id="select-level">
                        <option value="beginner">Начинающий</option>
                        <option value="intermediate">Средний уровень</option>
                        <option value="expert">Эксперт</option>
                    </select>
                </div>
                <div>
                    <fieldset>
                        <legend>Выберите опции и укажите цену:</legend>
                      
                        <div id="options-checkboxes">
                            <div class="options-row" id="options-basic">
                                <div>
                                    <input type="checkbox" id="checkbox-basic" name="basic">
                                    <label for="basic">Basic</label>
                                </div>
                                <div class="options-input hidden" id="price-basic">
                                    <label for="basic-price">Стоимость</label>
                                    <input type="number" name="basic-price">
                                </div>
                            </div>
                        
                            <div class="options-row" id="options-extra">
                                <div>
                                    <input type="checkbox" id="checkbox-extra" name="extra">
                                    <label for="extra">Extra</label>
                                </div>
                                <div class="options-input hidden" id="price-extra">
                                    <label for="basic-price">Стоимость</label>
                                    <input type="number" name="extra-price">
                                </div>
                                <div class="options-error hidden">
                                    <span>Вы не можете добавить эту опцию, пока не будет выбрана предыдущая</span>
                                </div>
                            </div>

                            <div class="options-row" id="options-premium">
                                <div>
                                    <input type="checkbox" id="checkbox-premium" name="premium">
                                    <label for="premium">Premium</label>
                                </div>
                                <div class="options-input hidden" id="price-premium">
                                    <label for="basic-price">Стоимость</label>
                                    <input type="number" name="premium-price">
                                </div>
                                <div class="options-error hidden">
                                    <span>Вы не можете добавить эту опцию, пока не будет выбрана предыдущая</span>
                                </div>
                            </div>
                        </div>
                      </fieldset>
                </div>
            </div>
            <button class="form-button" id="course-back-to-2step-btn">Назад</button>
            <button class="form-button" id="course-confirm-btn">Подтвердить</button>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/course-preview.html
{% extends "base.html" %}
{% load static %}
{% block title %}Войти на сайт{% endblock title %}
{% block imports %}
<link href="{% static 'course-single.css' %}" rel="stylesheet">
<script src="{% static 'course-preview.js' %}" defer></script>
{% endblock imports %}  
{% block content %}
<p id="csrf-token">{% csrf_token %}</p>
<div class="invisible">
    <p id="course-id">{{ id }}</p>
    <svg id="icon-expand" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 9l6 6 6-6"/></svg>
    <svg id="icon-date" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
    <svg id="icon-language" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M15.54 8.46a5 5 0 0 1 0 7.07"></path></svg>
    <svg id="icon-check" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
    <svg id="icon-lesson" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="2.18" ry="2.18"></rect><line x1="7" y1="2" x2="7" y2="22"></line><line x1="17" y1="2" x2="17" y2="22"></line><line x1="2" y1="12" x2="22" y2="12"></line><line x1="2" y1="7" x2="7" y2="7"></line><line x1="2" y1="17" x2="7" y2="17"></line><line x1="17" y1="17" x2="22" y2="17"></line><line x1="17" y1="7" x2="22" y2="7"></line></svg>
    <svg id="icon-extra_file" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M13 2H6a2 2 0 0 0-2 2v16c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V9l-7-7z"/><path d="M13 3v6h6"/></svg>
    <svg id="icon-test" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg>
    <svg id="icon-homework" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 14.66V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h5.34"></path><polygon points="18 2 22 6 12 16 8 16 8 12 18 2"></polygon></svg>
    <svg id="icon-star" xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
</div>
<div id="course-header">
    <div id="course-header-content">
        <h1 id="course-name"></h1>
        <div id="course-short_description"></div>
        <div id="course-created_by">
            <span>Created by</span>
        </div>
        <div id="course-header-bottom">
            <svg class="course-header-icon">
                <use href="#icon-date"></use>
            </svg>
            <span>Last update <span id="course-date_updated"></span></span>
            <svg class="course-header-icon">
                <use href="#icon-language"></use>
            </svg>
            <span id="course-language"></span>
        </div>
        <div id="course-header-reviews">
            <span>Средняя оценка: <span id="course-reviews-rating"></span></span>
        </div>
    </div>
</div>
<template id="template-what_will_learn">
    <div class="what_will_learn-item">
        <svg class="what_will_learn-icon">
            <use href="#icon-check"></use>
        </svg>
        <span class="what_will_learn-text"></span>
    </div>
</template>
<div id="body-wrapper">
    <div id="side-menu">
        <img id="side-menu-cover" src="" alt="">
        <div id="side-menu-content">
            <div id="side-menu-paid" class="invisible">
                <span></span>
                <div id="side-menu-paid-content">

                </div>
                <span></span>
            </div>
            <h2 id="side-menu-price"></h2>
            <div id="buy-btn" class="form-button">Купить</div>
            <div id="side-menu-options-header">
            </div>
            <div id="side-menu-options">
                <span>Данная опция включает:</span>
                <div id="side-menu-options-content">
                    
                </div>
            </div>
            <div id="side-menu-upgrade" class="invisible">
                <span>Вы можете получить апгрейд всего за:</span>
                <h2 id="side-menu-upgrade-price"></h2>
                <div id="upgrade-btn" class="form-button">Апгрейд</div>
            </div>
        </div>
        <div id="side-menu-review" class="invisible">
            <div id="review-btn" class="form-button">Оставить отзыв</div>
        </div>
    </div>
    <div id="course-body">
        <!-- <div id="buy-basic" class="buy-course">Купить basic</div>
        <div id="buy-extra" class="buy-course">Купить extra</div>
        <div id="buy-premium" class="buy-course">Купить premium</div> -->
        
        <div id="course-what_will_learn">
            <h2>Чему вы научитесь:</h2>
            <div id="what_will_learn-items"></div>
        </div>
        <div id="content-title">
            <h2>Материалы курсы</h2>
        </div>
        <template id="template-requirements">
            <li class="course-requirement"></li>
        </template>
        <div id="course-requirements">
            <h2>Необходимые требования</h2>
            <ul></ul>
        </div>
        <div id="course-description">
            <h2>Подробное описание</h2>
            <div id="course-full_description"></div>
        </div>
        <div id="course-reviews">
            <h2>Отзывы о курсе</h2>
            <span>Отзывов: <span id="course-reviews-count"></span></span>
            <div id="course-reviews-btn" class="form-button">Посмотреть отзывы</div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/index.html
{% extends "base.html" %}
{% block title %}Index page{% endblock title %}
{% block content %}
<p>All is working</p>
{% endblock content %}